<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>dtm</string>
      <string>stm</string>
      <string>gtm</string>
    </array>
    <key>uuid</key>
    <string>A4D7C65B-1774-42E6-899B-FB615886BB30</string>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>ActionGUI</string>
    <key>scopeName</key>
    <string>source.actiongui</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#dataModelDef</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#roleDef</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#windowDef</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.double-slash.actiongui</string>
            <key>match</key>
            <string>//.*$</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.actiongui</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
          </dict>
        </array>
      </dict>
      <key>dataModelDef</key>
      <dict>
        <key>name</key>
        <string>meta.datamodel.actiongui</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#entityDef</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#enumDef</string>
          </dict>
        </array>
      </dict>
      <key>entityDef</key>
      <dict>
        <key>name</key>
        <string>meta.entity.actiongui</string>
        <key>begin</key>
        <string>(entity)\s+(\w+)\s+(\{)</string>
        <key>end</key>
        <string>\s*(\})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.actiongui</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.entity.actiongui</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#fieldDef</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
        </array>
      </dict>
      <key>fieldDef</key>
      <dict>
        <key>match</key>
        <string>\b(\S+)\s+(\w+)\s+(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#type</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.property.actiongui</string>
          </dict>
          <key>3</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b(oppositeTo)\s+(\w+)\b</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.association.actiongui</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.other.property.actiongui</string>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <key>type</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#primitiveType</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#collectionType</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#customType</string>
          </dict>
        </array>
      </dict>
      <key>primitiveType</key>
      <dict>
        <key>name</key>
        <string>support.type.primitive.actiongui</string>
        <key>match</key>
        <string>\b(Boolean|Integer|Real|String|LocalDate)\b</string>
      </dict>
      <key>customType</key>
      <dict>
        <key>name</key>
        <string>entity.name.type.actiongui</string>
        <key>match</key>
        <string>\b\w+\b</string>
      </dict>
      <key>collectionType</key>
      <dict>
        <key>name</key>
        <string>support.type.collection.actiongui</string>
        <key>begin</key>
        <string>\b(Set|Bag|OrderedSet|Sequence)(\()</string>
        <key>end</key>
        <string>\s*(\))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.type.collection.base.actiongui</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.generic.actiongui</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.generic.actiongui</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#primitiveType</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#customType</string>
          </dict>
        </array>
      </dict>
      <key>enumDef</key>
      <dict>
        <key>name</key>
        <string>meta.enum.actiongui</string>
        <key>begin</key>
        <string>(enum)\s+(\w+)\s+(\{)</string>
        <key>end</key>
        <string>\s*(\})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.actiongui</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.enum.actiongui</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.other.enum.actiongui</string>
            <key>match</key>
            <string>\w+</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
        </array>
      </dict>
      <key>roleDef</key>
      <dict>
        <key>name</key>
        <string>meta.role.actiongui</string>
        <key>begin</key>
        <string>(role)\s+(\w+)(\s+(extends)\s+(\w+))?\s*(\{)</string>
        <key>end</key>
        <string>\s*(\})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.actiongui</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.role.actiongui</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.other.extends.actiongui</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.role.actiongui</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#roleEntity</string>
          </dict>
        </array>
      </dict>
      <key>roleEntity</key>
      <dict>
        <key>name</key>
        <string>meta.role.entity.actiongui</string>
        <key>begin</key>
        <string>\b(\w+)\s*(\{)</string>
        <key>end</key>
        <string>\s*(\})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.entity.actiongui</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.permission.separator.actiongui</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#permission</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.role.entity.entry.withConstraint.actiongui</string>
            <key>begin</key>
            <string>\b(constrainedBy)\s*(\[)</string>
            <key>end</key>
            <string>\s*(\])</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.permission.constraint.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.block.ocl.actiongui</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.block.ocl.actiongui</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#oclContent</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>permission</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.other.permission.attribute.actiongui</string>
            <key>match</key>
            <string>\b(read|update|add|remove)\s*\((\w+)\)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.property.actiongui</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>variable.other.permission.overall.actiongui</string>
            <key>match</key>
            <string>\b(create|delete|fullAccess|read|update)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.actiongui</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>ocl</key>
      <dict>
        <key>name</key>
        <string>meta.embedded.ocl.actiongui</string>
        <key>begin</key>
        <string>(\[)</string>
        <key>end</key>
        <string>(\])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.block.ocl.actiongui</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.block.ocl.actiongui</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#oclContent</string>
          </dict>
        </array>
      </dict>
      <key>oclContent</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>support.constant.actiongui.ocl</string>
            <key>match</key>
            <string>\b(self|caller|value|target)\b</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#oclAccess</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#oclMember</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#oclEnumCase</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#oclJoin</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#oclLiteral</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#oclConditional</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.expression.gui.actiongui.ocl</string>
            <key>match</key>
            <string>(\$)(.+?)(\$)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.expression.gui.actiongui.ocl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#guiExpression</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.expression.gui.actiongui.ocl</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.actiongui.ocl</string>
            <key>match</key>
            <string>\b(and|or|not|xor|implies)\b|(=(?!=)|&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;|\+|-(?!&gt;)|\*|/|\|)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#type</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#oclGroup</string>
          </dict>
        </array>
        <key>repository</key>
        <dict>
          <key>oclExpressionList</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>punctuation.expressionList.separator.actiongui.ocl</string>
                <key>match</key>
                <string>,</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#oclContent</string>
              </dict>
            </array>
          </dict>
          <key>oclMember</key>
          <dict>
            <key>name</key>
            <string>meta.member.actiongui.ocl</string>
            <key>match</key>
            <string>(\.)(div|mod|abs|max|min|floor|round|size|concat|substring|toUpper|toLower|toInteger|toReal|toString|oclIsUndefined|oclIsInvalid)(\()(.*?)(\))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.chain.actiongui.ocl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.function.actiongui.ocl</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.parameters.actiongui.ocl</string>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#oclExpressionList</string>
                  </dict>
                </array>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.parameters.actiongui.ocl</string>
              </dict>
            </dict>
          </dict>
          <key>oclAccess</key>
          <dict>
            <key>name</key>
            <string>meta.access.actiongui.ocl</string>
            <key>match</key>
            <string>(-&gt;)(any|size|count|includes|excludes|includesAll|excludesAll|isEmpty|notEmpty|sum|exists|forall|isUnique|sortedBy|iterate|union|intersection|including|excluding|symmetricDifference|select|reject|collect|collectNested|flatten|append|prepend|insertAt|subSequence|at|first|last|indexOf|asSequence|asSet|asBag|asOrderedSet|oclIsUndefined)(\()(.*?)(\))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.access.actiongui.ocl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.function.actiongui.ocl</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.parameters.actiongui.ocl</string>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#oclExpressionList</string>
                  </dict>
                </array>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.parameters.actiongui.ocl</string>
              </dict>
            </dict>
          </dict>
          <key>oclEnumCase</key>
          <dict>
            <key>name</key>
            <string>meta.enumCase.actiongui.ocl</string>
            <key>match</key>
            <string>(::)(\w+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.enumCase.actiongui.ocl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.other.enum.actiongui.ocl</string>
              </dict>
            </dict>
          </dict>
          <key>oclJoin</key>
          <dict>
            <key>name</key>
            <string>meta.join.actiongui.ocl</string>
            <key>match</key>
            <string>(\.)(\w+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.join.actiongui.ocl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.property.actiongui.ocl</string>
              </dict>
            </dict>
          </dict>
          <key>oclLiteral</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.language.actiongui.ocl</string>
                <key>match</key>
                <string>\b(true|false|null|invalid)\b</string>
              </dict>
              <dict>
                <key>name</key>
                <string>constant.numeric.actiongui.ocl</string>
                <key>match</key>
                <string>(-)?\d+(\.\d+)?</string>
              </dict>
              <dict>
                <key>name</key>
                <string>constant.string.actiongui.ocl</string>
                <key>match</key>
                <string>\'.*?(?&lt;!\\)\'</string>
              </dict>
            </array>
          </dict>
          <key>oclConditional</key>
          <dict>
            <key>match</key>
            <string>\b(if)\s+(.*)\s+(then)\s+(.*)\s+(else)\s+(.*)\s+(endif)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.if.actiongui.ocl</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#oclContent</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.then.actiongui.ocl</string>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#oclContent</string>
                  </dict>
                </array>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>keyword.control.else.actiongui.ocl</string>
              </dict>
              <key>6</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#oclContent</string>
                  </dict>
                </array>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>keyword.control.endif.actiongui.ocl</string>
              </dict>
            </dict>
          </dict>
          <key>oclGroup</key>
          <dict>
            <key>begin</key>
            <string>(\()</string>
            <key>end</key>
            <string>(\))</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.group.actiongui.ocl</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.group.actiongui.ocl</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#oclContent</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <key>windowDef</key>
      <dict>
        <key>name</key>
        <string>meta.window.actiongui</string>
        <key>begin</key>
        <string>\b(Window)\s+(\w+)\s+(\{)</string>
        <key>end</key>
        <string>(\})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.class.actiongui</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.window.actiongui</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#widgetContents</string>
          </dict>
        </array>
      </dict>
      <key>widgetContents</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#widgetDef</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.property.gui.actiongui</string>
            <key>match</key>
            <string>\b(\S+)\s+(\w+)\b\s+(:=)\s+(\[.*\])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#type</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.property.actiongui</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.actiongui</string>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#ocl</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.event.actiongui</string>
            <key>begin</key>
            <string>\b(event)\s+(\w+)\s*((\()(\w+)(\)))?\s+(\{)</string>
            <key>end</key>
            <string>\s*(\})</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.event.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.event.actiongui</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctiation.parameters.actiongui</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.actiongui</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>punctiation.parameters.actiongui</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#guiCode</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.columns.actiongui</string>
            <key>begin</key>
            <string>\b(columns)\s+(\{)</string>
            <key>end</key>
            <string>(\})</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.columns.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>punctuation.column.colon.actiongui</string>
                <key>match</key>
                <string>:</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#ocl</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#widgetDef</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>widgetDef</key>
      <dict>
        <key>name</key>
        <string>meta.widget.actiongui</string>
        <key>begin</key>
        <string>\b(Label|ComboBox|Table|Button|Label|TextField|PasswordField|BooleanField|DateField|DateTimeField)\s+(\w+)\s+(\{)</string>
        <key>end</key>
        <string>(\})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.class.actiongui</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.type.widget.actiongui</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.block.actiongui</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#widgetContents</string>
          </dict>
        </array>
      </dict>
      <key>guiCode</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#guiControlFlow</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#guiDataAction</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#guiFunctionCall</string>
          </dict>
        </array>
      </dict>
      <key>guiControlFlow</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.control.if.actiongui</string>
            <key>begin</key>
            <string>\b(if)\s*(\[.*\])\s*(\{)</string>
            <key>end</key>
            <string>\s*(\})</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.if.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#ocl</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#guiCode</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.control.else.actiongui</string>
            <key>begin</key>
            <string>\b(else)\s*(\{)</string>
            <key>end</key>
            <string>\s*(\})</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.else.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#guiCode</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.control.try.actiongui</string>
            <key>begin</key>
            <string>\b(try)\s*(\{)</string>
            <key>end</key>
            <string>\s*(\})</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.try.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#guiCode</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.control.catch.actiongui</string>
            <key>begin</key>
            <string>\b(catch)\s*(\()(SecurityException|ModelException)(\))\s*(\{)</string>
            <key>end</key>
            <string>\s*(\})</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.catch.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.actiongui</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.type.exception.actiongui</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.actiongui</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#guiCode</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.control.foreach.actiongui</string>
            <key>begin</key>
            <string>\b(foreach)\s+(\w+)\s+(in)\s*(\[.*\])\s*(\{)</string>
            <key>end</key>
            <string>\s*(\})</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.foreach.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.parameter.actiongui</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.control.foreach.in.actiongui</string>
              </dict>
              <key>4</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#ocl</string>
                  </dict>
                </array>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.actiongui</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#guiCode</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>guiDataAction</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.dataAction.create.actiongui</string>
            <key>match</key>
            <string>([\w\.]+)\s*(:=)\s*(new)\s+(\w+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#guiExpression</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.gui.actiongui</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.new.actiongui</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.class.actiongui</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.dataAction.delete.actiongui</string>
            <key>match</key>
            <string>\b(delete)\s+(\[.*\])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.delete.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#ocl</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.dataAction.read.actiongui</string>
            <key>match</key>
            <string>([\w\.]+)\s*(:=)\s*(\[.*\])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#guiExpression</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.gui.actiongui</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#ocl</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.dataAction.update.actiongui</string>
            <key>match</key>
            <string>(\[.*\])\s*(:=|\+=|-=)\s*(\[.*\])</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#ocl</string>
                  </dict>
                </array>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.gui.actiongui</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#ocl</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>guiFunctionCall</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.functionCall.space.actiongui</string>
            <key>match</key>
            <string>\b(\w+)\s+([\w\.]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.function.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#guiExpression</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.functionCall.parens.actiongui</string>
            <key>match</key>
            <string>\b(\w+)\s*(\()(.*)(\))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.function.actiongui</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.actiongui</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#oclList</string>
                  </dict>
                </array>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.actiongui</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>oclList</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>punctuation.expressionList.separator.actiongui.ocl</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ocl</string>
          </dict>
        </array>
      </dict>
      <key>guiExpression</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>meta.expression.gui.actiongui</string>
            <key>match</key>
            <string>\b(\w+)(\.(\w+))*\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#type</string>
                  </dict>
                </array>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.property.actiongui</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#ocl</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>